services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-fila-zero
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=fila_zero 
    ports: 
      - '3309:3306'
    networks: 
      - fila-zero-network
    volumes:
      - mysql-data:/var/lib/mysql  

networks:
  fila-zero-network:
    driver: bridge

volumes:
  mysql-data:
